Description: CICD pipeline for cfn-certificate-resource
Parameters:
  GithubToken:
    Type: String
    NoEcho: true
    Description: OAuth token for the Github organization.  Needs read/write access to repos and repo hooks

  GithubOwner:
    Type: String
    Description: Owner of the github repository to track

  GithubRepo:
    Type: String
    Description: Name of the github repository to track

  GithubBranch:
    Type: String
    Description: Name of the github branch to track

Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket

  ArtifactStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactStore
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:*Object
            Resource:
              - !Sub arn:aws:s3:::${ArtifactStore}
              - !Sub arn:aws:s3:::${ArtifactStore}/*
            Principal:
              AWS:
                - !Ref AWS::AccountId
                - !ImportValue cfn-metadata:DevAgentRoleArn
                - !ImportValue cfn-metadata:ProdAgentRoleArn

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE

  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-pipeline
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
        EncryptionKey:
          Id: !ImportValue cfn-utilities:ArtifactKeyArn
          Type: KMS
      RoleArn: !ImportValue cfn-utilities:MasterRoleArn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              OutputArtifacts:
                - Name: sourceCode
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubToken
                PollForSourceChanges: false
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: buildResults
              Configuration:
                ProjectName: !Ref BuildProject
        - Name: Shared
          Actions:
            - Name: Deploy
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
              OutputArtifacts:
                - Name: samlProviderOutputs
              Configuration:
                StackName: cfn-saml-provider-resource
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::saml-provider.template.yml
                RoleArn: !ImportValue cfn-utilities:MasterRoleArn
                Capabilities: CAPABILITY_IAM
                OutputFileName: saml-provider-outputs.json
        - Name: Dev
          Actions:
            - Name: Deploy
              RoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
                - Name: samlProviderOutputs
              Configuration:
                StackName: cfn-saml-provider-resource
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::cross-account.template.yml
                TemplateConfiguration: buildResults::cross-account.config.json
                RoleArn: !ImportValue cfn-metadata:DevAgentRoleArn
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  {
                    "SamlProviderRoleArn": { "Fn::GetParam": [ "samlProviderOutputs", "saml-provider-outputs.json", "SamlProviderRoleArn" ] },
                    "SamlProviderLambdaArn": { "Fn::GetParam": [ "samlProviderOutputs", "saml-provider-outputs.json", "SamlProviderLambdaArn" ] }
                  }
        - Name: Prod
          Actions:
            - Name: Approve
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              InputArtifacts: []
              OutputArtifacts: []
            - Name: Deploy
              RunOrder: 2
              RoleArn: !ImportValue cfn-metadata:ProdAgentRoleArn
              ActionTypeId:
                Category: Deploy
                Provider: CloudFormation
                Owner: AWS
                Version: 1
              InputArtifacts:
                - Name: buildResults
                - Name: samlProviderOutputs
              Configuration:
                StackName: cfn-saml-provider-resource
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::cross-account.template.yml
                TemplateConfiguration: buildResults::cross-account.config.json
                RoleArn: !ImportValue cfn-metadata:ProdAgentRoleArn
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  {
                    "SamlProviderRoleArn": { "Fn::GetParam": [ "samlProviderOutputs", "saml-provider-outputs.json", "SamlProviderRoleArn" ] },
                    "SamlProviderLambdaArn": { "Fn::GetParam": [ "samlProviderOutputs", "saml-provider-outputs.json", "SamlProviderLambdaArn" ] }
                  }
